# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-gradle

name: Java CI/CD with Gradle and Docker

# event trigger
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main


permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      ## jdk setting
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      ## MySQL setting
      - name: Setup MySQL
        uses: samin/mysql-action@v1
        with:
          character set server: 'utf8'
          mysql database: 'runninghi'
          mysql user: ${{ secrets.MYSQL_USERNAME }}
          mysql password: ${{ secrets.MYSQL_PASSWORD }}

      ## application.yml 파일을 생성합니다.
      - name: make application.yml
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.APPLICATION }}" > ./application.yml
        shell: bash

      ## application-dev.yml 파일을 생성합니다.
      - name: make application-dev.yml
        if: contains(github.ref, 'dev')
        run: |
          cd ./src/main/resources
          touch ./application-dev.yml
          echo "${{ secrets.APPLICATION_DEV }}" > ./application-dev.yml
        shell: bash

      ## application-prod.yml 파일을 생성합니다.
      - name: make application-prod.yml
        if: contains(github.ref, 'master')
        run: |
          cd ./src/main/resources
          touch ./application-prod.yml
          echo "${{ secrets.APPLICATION_PROD }}" > ./application-prod.yml
        shell: bash

      ## jwt.yml 파일을 생성합니다.
      - name: make jwt.yml
        run: |
          cd ./src/main/resources
          touch ./jwt.yml
          echo "${{ secrets.JWT }}" > ./jwt.yml
        shell: bash

      ## gradlew 실행 권한 부여
      - name: Grant execute permisson for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle (without Test)
        run: ./gradlew clean build -x test --stacktrace

      ########## CD(Continuous Delivery/Deployment) ##########
      ## docker hub에 로그인하고 runninghi-dev에 이미지를 빌드 & push 합니다.
      - name: Docker build & push to dev repo
        if: contains(github.ref, 'dev')
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME_DEV }}" -p "${{ secrets.DOCKER_PASSWORD_DEV }}"
          docker build -f Dockerfile-dev -t "${{ secrets.DOCKER_USERNAME_DEV }}"/runninghi-dev .
          docker push "${{ secrets.DOCKER_USERNAME_DEV }}"/runninghi-dev

      ## docker hub에 로그인하고 runninghi-prod에 이미지를 빌드 & push 합니다.
      - name: Docker build & push to prod repo
        if: contains(github.ref, 'master')
        run: |
          docker login -u "${{ secrets.DOCKER_USERNAME_PROD }}" -p "${{ secrets.DOCKER_PASSWORD_PROD }}"
          docker build -f Dockerfile-prod -t "${{ secrets.DOCKER_USERNAME_PROD }}"/runninghi-prod .
          docker push "${{ secrets.DOCKER_USERNAME_PROD }}"/runninghi-prod

      ## AWS EC2에 접속하고 develop을 배포합니다.
      - name: Deploy to Dev
        uses: appleboy/ssh-action@master
        id: deploy-dev
        if: contains(github.ref, 'dev')
        with:
          host: ${{ secrets.HOST_DEV }} # EC2 인스턴스 퍼블릭 DNS
          username: ${{ secrets.USERNAME }} # 인스턴스를 시작하는 데 사용되는 AMI에 정의된 사용자 이름을 입력합니다. 사용자 지정 사용자 이름을 정의하지 않은 경우 기본 사용자 이름인 ubuntu을(를) 사용합니다.
          key: ${{ secrets.PRIVATE_KEY }} # 키 페어의 pem 키
          # sudo docker-compose up -d
          script: |
            sudo docker login -u "${{ secrets.DOCKER_USERNAME_DEV }}" -p "${{ secrets.DOCKER_PASSWORD_DEV }}"
            sudo docker stop runninghi_spring_boot_dev
            sudo docker rm -f $(sudo docker ps --filter 'status=exited' -a -q)
            sudo docker pull "${{ secrets.DOCKER_USERNAME_DEV }}"/runninghi-dev
            sudo docker run --name runninghi_spring_boot_dev -d --log-driver=syslog -p 8081:8081 -e SPRING_PROFILES_ACTIVE=dev "${{ secrets.DOCKER_USERNAME_DEV }}"/runninghi-dev
            sudo docker image prune -a -f

      ## AWS EC2에 접속하고 production을 배포합니다.
      - name: Deploy to Prod
        uses: appleboy/ssh-action@master
        id: deploy-prod
        if: contains(github.ref, 'master')
        with:
          host: ${{ secrets.HOST_PROD }} # EC2 인스턴스 퍼블릭 DNS
          username: ${{ secrets.USERNAME }} # 인스턴스를 시작하는 데 사용되는 AMI에 정의된 사용자 이름을 입력합니다. 사용자 지정 사용자 이름을 정의하지 않은 경우 기본 사용자 이름인 ubuntu을(를) 사용합니다.
          key: ${{ secrets.PRIVATE_KEY }} # 키 페어의 pem 키
          #            sudo docker run --name runninghi_spring_boot_prod -d --log-driver=syslog -p 8082:8082 -e SPRING_PROFILES_ACTIVE=prod "${{ secrets.DOCKER_USERNAME_PROD }}"/runninghi-prod
          script: |
            sudo docker login -u "${{ secrets.DOCKER_USERNAME_PROD }}" -p "${{ secrets.DOCKER_PASSWORD_PROD }}"
            sudo docker stop runninghi_spring_boot_prod
            sudo docker rm -f $(sudo docker ps --filter 'status=exited' -a -q)
            sudo docker pull "${{ secrets.DOCKER_USERNAME_PROD }}"/runninghi-prod
            sudo docker-compose up -d
            sudo docker image prune -a -f
